export {
    REQUIREMENTS,
    GOALS,
    GAME_NAME
}

// Only need to have locations and ids that will be used for requirements and goals
class LOCATIONS {
    static TREE1 = 600;
    static TREE2 = 601;
    static TREE3 = 602;
    static TREE4 = 603;
    static TREE5 = 604;
    static TREE6 = 605;
    static TREE7 = 606;
    static TREE8 = 607;
    static TREE9 = 608;
    static TREE10 = 609;
}

// Only need to have items and ids that will be used for requirements
class ITEMS {
    static MAGPIE1 = 11490;
    static MAGPIE2 = 11491;
    static MAGPIE3 = 11492;
}

let GAME_NAME = "Chatipelago";

let REQUIREMENTS = {
    [LOCATIONS.TREE1]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE2]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE3]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE4]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE5]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE6]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE7]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE8]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE9]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
    [LOCATIONS.TREE10]: [ITEMS.MAGPIE1, ITEMS.MAGPIE2, ITEMS.MAGPIE3],
}

let GOALS = [LOCATIONS.TREE1, LOCATIONS.TREE2, LOCATIONS.TREE3, LOCATIONS.TREE4, LOCATIONS.TREE5,
    LOCATIONS.TREE6, LOCATIONS.TREE7, LOCATIONS.TREE8, LOCATIONS.TREE9, LOCATIONS.TREE10]
