name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            platform: win
            extension: .exe
          - os: ubuntu-latest
            platform: linux
            extension: ''
          - os: macos-latest
            platform: macos
            extension: ''
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build executable
        run: npx pkg start-chatipelago.js --targets node18-${{ matrix.platform }}-x64 --output-path dist/chatipelago${{ matrix.extension }}
        env:
          PKG_CACHE_PATH: ${{ runner.temp }}/pkg-cache

      - name: Package with assets (Windows)
        if: matrix.platform == 'win'
        run: |
          mkdir dist\chatipelago-win-x64
          move dist\chatipelago.exe dist\chatipelago-win-x64\
          xcopy /E /I customConfig dist\chatipelago-win-x64\customConfig
          copy icon.png dist\chatipelago-win-x64\
          copy package.json dist\chatipelago-win-x64\
          if exist README.md copy README.md dist\chatipelago-win-x64\
        shell: cmd

      - name: Package with assets (Unix)
        if: matrix.platform != 'win'
        run: |
          mkdir -p dist/chatipelago-${{ matrix.platform }}-x64
          mv dist/chatipelago${{ matrix.extension }} dist/chatipelago-${{ matrix.platform }}-x64/
          cp -r customConfig dist/chatipelago-${{ matrix.platform }}-x64/
          cp icon.png dist/chatipelago-${{ matrix.platform }}-x64/
          cp package.json dist/chatipelago-${{ matrix.platform }}-x64/
          cp README.md dist/chatipelago-${{ matrix.platform }}-x64/ 2>/dev/null || true

      - name: Create archive (Windows)
        if: matrix.platform == 'win'
        uses: thedoctor0/zip-release@v0.7.1
        with:
          type: 'zip'
          filename: 'dist/chatipelago-win-x64.zip'
          path: 'dist/chatipelago-win-x64'
          exclusions: '*.zip *.tar.gz'

      - name: Create archive (Unix)
        if: matrix.platform != 'win'
        run: |
          cd dist/chatipelago-${{ matrix.platform }}-x64
          tar -czf ../chatipelago-${{ matrix.platform }}-x64.tar.gz *

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chatipelago-${{ matrix.platform }}-x64
          path: |
            dist/chatipelago-${{ matrix.platform }}-x64/chatipelago${{ matrix.extension }}
            dist/chatipelago-${{ matrix.platform }}-x64.*
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.zip
            dist/**/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

