name: Build Executable

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [20.x, 22.x]
        exclude:
          # macOS builds are slower, only build latest Node
          - os: macos-latest
            node-version: 20.x
    name: Build on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build executable
        run: npm run build
      
      - name: Verify executable
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            if [ ! -f "chatipelago.exe" ]; then
              echo "Error: chatipelago.exe not found"
              exit 1
            fi
            ls -lh chatipelago.exe
          else
            if [ ! -f "chatipelago" ]; then
              echo "Error: chatipelago not found"
              exit 1
            fi
            chmod +x chatipelago
            ls -lh chatipelago
          fi
      
      - name: Create zip archive (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $zipName = "chatipelago-windows-node${{ matrix.node-version }}.zip"
          $filesToZip = @('chatipelago.exe', 'README.md', 'LICENSE') | Where-Object { Test-Path $_ }
          if ($filesToZip.Count -eq 0) {
            Write-Error "No files found to zip"
            exit 1
          }
          Get-ChildItem $filesToZip | Compress-Archive -DestinationPath $zipName -Force
          Write-Host "Created: $zipName ($(Get-Item $zipName | Select-Object -ExpandProperty Length) bytes)"
      
      - name: Create zip archive (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ZIP_NAME="chatipelago-${{ matrix.os }}-node${{ matrix.node-version }}.zip"
          zip -r "$ZIP_NAME" chatipelago README.md LICENSE 2>/dev/null || {
            echo "Error: Failed to create zip archive"
            exit 1
          }
          echo "Created: $ZIP_NAME ($(stat -f%z "$ZIP_NAME" 2>/dev/null || stat -c%s "$ZIP_NAME" 2>/dev/null || echo 'unknown') bytes)"
      
      - name: Upload zip archive (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: chatipelago-windows-node${{ matrix.node-version }}
          path: chatipelago-windows-node${{ matrix.node-version }}.zip
          retention-days: 30
      
      - name: Upload zip archive (Unix)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: chatipelago-${{ matrix.os }}-node${{ matrix.node-version }}
          path: chatipelago-${{ matrix.os }}-node${{ matrix.node-version }}.zip
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version from tag
        if: github.event_name != 'release'
        id: tag_version
        shell: bash
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Release tag: $TAG"
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event_name == 'release' && github.event.release.tag_name || steps.tag_version.outputs.tag }}
          name: Release ${{ github.event_name == 'release' && github.event.release.tag_name || steps.tag_version.outputs.tag }}
          files: artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
